In [8]:
import numpy as np

Understanding Array and its functions present in Numpy

In [12]:
arr = np.array([1,2,3,4])
arr
# print(arr)

array([1, 2, 3, 4])

In [14]:
arr.size

4

In [16]:
arr.shape

(4,)

In [17]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [29]:
arr.resize(4,1)
arr

array([[1],
       [2],
       [3],
       [4]])

In [55]:
np.random.ranf()

0.7697371091329828



Array indexing

In [59]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
print(arr[4])

15


In [64]:
print(arr[4:8])

[15 16 17 18]


In [66]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
print(arr[2:3,2:4])

[[13 14]]


Array Operations
