In [3]:
import numpy as np

**Valid Sudoku**

In [24]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8,4, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

we have to check weather the soduku is valid or not
so we check the row and col sum weather for each row anc col it is 45 or not if yes then valid else not 

**General Questions**

In [25]:
b=np.sum(s,axis=1)
for i in b:
    if(i!=45):
        print("not valid")
        break
else:
    print("valid")

not valid


In [26]:
c=np.sum(s,axis=0)
for i in c:
    if(i!=45):
        print("not valid")
        break
else:
    print("valid")

not valid


In [103]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [27]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [33]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [35]:
#Extract Math marks of all students.
data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [62]:
#Find the highest Science mark.
np.max(data[:,2:3])

np.int64(95)

In [90]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [87]:
#Find how many students are younger than 19.


array([], shape=(5, 0), dtype=int64)

In [91]:
#Increase Math marks of all students by 5.
data[:,1:2]=data[:,1:2]+5
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [97]:
#Calculate the average marks in each subject (column-wise mean).
a=np.mean(data[:,2:3])
b=np.mean(data[:,1:2])
print(a,b)

83.2 86.6


In [100]:

#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [106]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])